import axios from "axios";
import React, { useEffect, useMemo, useState } from "react";
import { FaCalendarAlt, FaToggleOn } from "react-icons/fa";
import { MdOutlineLocalOffer } from "react-icons/md";
import { server_url } from "../../../App";
import { toast } from "react-toastify";

const initialForm = { couponCode:"", offerTitle:"", description:"", audience:"customer", benefitType:"CUSTOMER_DISCOUNT", serviceId:[], discountType:"percentage", discountValue:"", minBookingAmount:"", maxDiscount:"", rewardType:"wallet_credits", rewardValue:"", startDate:"", endDate:"", usageLimit:"", perUserLimit:1, newCustomerOnly:false, isActive:true };

const OfferForm = () => {
  const [services,setServices]=useState([]); const [servicesLoading,setServicesLoading]=useState(true); const [loading,setLoading]=useState(false); const [formData,setFormData]=useState(initialForm);
  const isProfessional=formData.audience==="professional", isPercentage=formData.discountType==="percentage";
  useEffect(()=>{ let mounted=true; axios.get(`${server_url}/api/user/get-services`).then(r=>{const list=r.data?.services||r.data?.data||[]; if(mounted)setServices(Array.isArray(list)?list:[]);}).catch(()=>{if(mounted)toast.error("Unable to load services");}).finally(()=>{if(mounted)setServicesLoading(false);}); return()=>{mounted=false;};},[]);
  const selectedServiceNames=useMemo(()=>services.filter(s=>formData.serviceId.includes(s._id)).map(s=>s.name),[services,formData.serviceId]);
  const change=e=>{const {name,value,type,checked}=e.target;setFormData(p=>({...p,[name]:type==="checkbox"?checked:value}));};
  const audience=a=>setFormData(p=>({...p,audience:a,benefitType:a==="customer"?"CUSTOMER_DISCOUNT":"PROFESSIONAL_REWARD",discountValue:"",minBookingAmount:"",maxDiscount:"",rewardValue:"",serviceId:[],newCustomerOnly:false,perUserLimit:a==="professional"?1:p.perUserLimit||1}));
  const toggle=id=>setFormData(p=>({...p,serviceId:p.serviceId.includes(id)?p.serviceId.filter(x=>x!==id):[...p.serviceId,id]}));
  const submit=async e=>{e.preventDefault();if(!formData.couponCode.trim())return toast.error("Enter a coupon code.");if(!formData.offerTitle.trim())return toast.error("Enter an offer title.");if(!formData.startDate||!formData.endDate)return toast.error("Select validity dates.");if(new Date(formData.endDate)<=new Date(formData.startDate))return toast.error("End date must be after start date.");if(!isProfessional){const v=Number(formData.discountValue);if(!Number.isFinite(v)||v<=0)return toast.error("Enter a discount greater than ₹0.");if(isPercentage&&v>100)return toast.error("Percentage discount cannot exceed 100%.");if(!isPercentage&&formData.maxDiscount!=="")return toast.error("Max discount is only for percentage coupons.");}else if(!Number.isFinite(Number(formData.rewardValue))||Number(formData.rewardValue)<1)return toast.error("Professional reward must be at least 1 credit.");try{setLoading(true);await axios.post(`${server_url}/api/admin/create-offer`,{...formData,audience:[formData.audience],discountValue:isProfessional?null:Number(formData.discountValue),minBookingAmount:!isProfessional&&formData.minBookingAmount!==""?Number(formData.minBookingAmount):null,maxDiscount:!isProfessional&&isPercentage&&formData.maxDiscount!==""?Number(formData.maxDiscount):null,rewardValue:isProfessional?Number(formData.rewardValue):null,usageLimit:formData.usageLimit===""?null:Number(formData.usageLimit),perUserLimit:isProfessional?1:Number(formData.perUserLimit)},{withCredentials:true});toast.success("Coupon created successfully");setFormData(initialForm);}catch(err){toast.error(err.response?.data?.message||"Failed to create coupon");}finally{setLoading(false);}};
  return <div className="container py-4"><div className="card bg-dark text-light shadow-lg border-0 rounded-4 p-4"><div className="d-flex align-items-center mb-2"><MdOutlineLocalOffer size={28} className="me-2 text-warning"/><div><h3 className="mb-0 fw-bold">Create Coupon</h3><small className="text-light opacity-75">Create one campaign for one audience. The recipient claims it using the coupon code.</small></div></div><form onSubmit={submit}><div className="alert alert-info py-2 small"><strong>Tip:</strong> Leave Services empty for all services, or select specific services.</div>
    <div className="row"><div className="col-md-6 mb-3"><label className="form-label fw-semibold">Coupon Code</label><input className="form-control" name="couponCode" value={formData.couponCode} onChange={change} placeholder="WELCOME200" maxLength={30} required/><small className="text-secondary">3–30 characters: letters, numbers, - or _. Saved uppercase.</small></div><div className="col-md-6 mb-3"><label className="form-label fw-semibold">Offer Title</label><input className="form-control" name="offerTitle" value={formData.offerTitle} onChange={change} placeholder="Welcome ₹200 off" required/><small className="text-secondary">Use a clear campaign name.</small></div></div>
    <div className="mb-4"><label className="form-label fw-semibold">Audience</label><div className="row g-2">{["customer","professional"].map(a=><div className="col-md-6" key={a}><button type="button" className={`btn w-100 text-start ${formData.audience===a?"btn-primary":"btn-outline-secondary"}`} onClick={()=>audience(a)}><strong>{a==="customer"?"Customer":"Professional"}</strong><span className="d-block small">{a==="customer"?"Booking discount":"Wallet-credit reward"}</span></button></div>)}</div><small className="text-secondary">Choose one audience to avoid conflicting financial rules.</small></div>
    <div className="mb-4"><label className="form-label fw-semibold">Applicable Services</label><div className="border rounded-3 p-3 bg-white text-dark">{servicesLoading?<div className="small text-muted">Loading services...</div>:services.length===0?<div className="small text-muted">No services available.</div>:<div className="row g-2">{services.map(s=><div className="col-12 col-md-4" key={s._id}><label className="d-flex align-items-center gap-2 border rounded-3 p-2 h-100"><input type="checkbox" checked={formData.serviceId.includes(s._id)} onChange={()=>toggle(s._id)}/><span>{s.name}</span></label></div>)}</div>}<small className="text-muted d-block mt-2">{selectedServiceNames.length?`Selected: ${selectedServiceNames.join(", ")}`:"No service selected = all services."}</small></div></div>
    {!isProfessional?<><div className="row"><div className="col-md-6 mb-3"><label className="form-label fw-semibold">Discount Type</label><select className="form-select" name="discountType" value={formData.discountType} onChange={change}><option value="percentage">Percentage (%)</option><option value="flat">Flat Amount (₹)</option></select></div><div className="col-md-6 mb-3"><label className="form-label fw-semibold">Discount Value</label><input type="number" min="0.01" step="0.01" className="form-control" name="discountValue" value={formData.discountValue} onChange={change} required/><small className="text-secondary">{isPercentage?"Enter 1–100. Example: 10 means 10% off.":"Enter the amount. ₹200 is valid."}</small></div></div><div className="row"><div className="col-md-6 mb-3"><label className="form-label">Minimum Booking Amount</label><input type="number" min="0" step="0.01" className="form-control" name="minBookingAmount" value={formData.minBookingAmount} onChange={change}/><small className="text-secondary">Optional minimum eligible booking value.</small></div><div className="col-md-6 mb-3"><label className="form-label">Maximum Discount</label><input type="number" min="0.01" step="0.01" disabled={!isPercentage} className="form-control" name="maxDiscount" value={formData.maxDiscount} onChange={change}/><small className="text-secondary">Only for percentage coupons.</small></div></div><div className="form-check form-switch mb-4"><input type="checkbox" className="form-check-input" name="newCustomerOnly" checked={formData.newCustomerOnly} onChange={change}/><label className="form-check-label"><FaToggleOn className="me-2 text-success"/>New Customers Only</label><small className="d-block text-secondary">Use for a first-booking campaign.</small></div></>:<div className="alert alert-warning"><strong>Professional reward:</strong> this is not a booking discount. It grants wallet credits when claimed.<div className="mt-2"><label className="form-label fw-semibold text-dark">Reward Credits</label><input type="number" min="1" step="1" className="form-control" name="rewardValue" value={formData.rewardValue} onChange={change} required/><small className="text-dark">Example: 500 means 500 Fixkar credits.</small></div></div>}
    <div className="row"><div className="col-md-6 mb-3"><label className="form-label"><FaCalendarAlt className="me-2"/>Start Date</label><input type="date" className="form-control" name="startDate" value={formData.startDate} onChange={change} required/><small className="text-secondary">Cannot be claimed before this date.</small></div><div className="col-md-6 mb-3"><label className="form-label"><FaCalendarAlt className="me-2"/>End Date</label><input type="date" className="form-control" name="endDate" value={formData.endDate} onChange={change} required/><small className="text-secondary">Expires after this date.</small></div></div><div className="row"><div className="col-md-6 mb-3"><label className="form-label">Global Usage Limit</label><input type="number" min="1" step="1" className="form-control" name="usageLimit" value={formData.usageLimit} onChange={change} placeholder="Empty = unlimited"/><small className="text-secondary">Maximum successful redemptions.</small></div><div className="col-md-6 mb-3"><label className="form-label">Per User Limit</label><input type="number" min="1" step="1" className="form-control" name="perUserLimit" value={formData.perUserLimit} onChange={change} disabled={isProfessional}/><small className="text-secondary">Maximum successful uses per customer. Professional rewards are one-time.</small></div></div><div className="form-check form-switch mb-4"><input type="checkbox" className="form-check-input" name="isActive" checked={formData.isActive} onChange={change}/><label className="form-check-label"><FaToggleOn className="me-2 text-warning"/>Active Coupon</label><small className="d-block text-secondary">Turn off to pause without deleting history.</small></div><button type="submit" className="btn btn-warning w-100 fw-bold py-2" disabled={loading}>{loading?"Creating...":"Create Coupon"}</button></form></div></div>;
};
export default OfferForm;
